export const vendorFormDefaultValues = {
    basicInfo: {
        vendor_name: "",
        vendor_code: "",
        vendor_category: "",
        gst_number: "",
        pan_number: "",
        payment_terms: "",
    },
    address: {
        street_address: "",
        city: "",
        state: "",
        country: "",
        pincode: "",
    },
    contactInfo: {
        contact_person_name: "",
        designation: "",
        email: "",
        mobile_number: "",
        alternate_phone: "",
        company_website: "",
    },
    bankDetails: {
        bank_name: "",
        account_number: "",
        ifsc_code: "",
        account_type: "",
        branch_name: "",
    },
    certificationsCompliance: {
        iso_9001_2015: false,
        msme_registered: false,
        dpiit_startup_registration: false,
        gmp_certified: false,
    },
    documents: {
        pan_document: "",
        aadhaar_document: "",
        bank_statement: "",
        gst_certificate: "",
        certification_document: "",
    },
}
export const vendorFormFields = {
    basicInfo: {
        label: "Basic Information",
       fields: [{
        name: "vendor_name",
        label: "Vendor Name",
        placeholder: "Enter Vendor Name",
        type: "text",
        required: true,
        errorMessage: "Vendor Name is required",
       },
       {
        name: "vendor_code",
        label: "Vendor Code",
        placeholder: "Enter Vendor Code",
        type: "text",
        required: true,
        errorMessage: "Vendor Code is required",
       },
       {
        name: "vendor_category",
        label: "Vendor Category",
        placeholder: "Select Vendor Category",
        type: "select",
        required: true,
        errorMessage: "Vendor Category is required",
        options: [
            { label: "Raw Materials", value: "raw_materials" },
            { label: "IT Services", value: "it_services" },
            { label: "Logistics", value: "logistics" },
            { label: "Electronics", value: "electronics" },
            { label: "Pharmaceuticals", value: "pharmaceuticals" },
            { label: "Energy", value: "energy" },
            { label: "Construction", value: "construction" },
            { label: "Furniture", value: "furniture" },
            { label: "Chemical & Petrochem", value: "chemical_petrochem" },
        ],
       },
       {
        name: "gst_number",
        label: "GST Number",
        placeholder: "Enter GST Number",
        type: "text",
        required: true,
        errorMessage: "GST Number is required",
       },
       {
        name: "pan_number",
        label: "PAN Number",
        placeholder: "Enter PAN Number",
        type: "text",
        required: true,
        errorMessage: "PAN Number is required",
       },
       {
        name: "payment_terms",
        label: "Payment Terms",
        placeholder: "Select Payment Terms",
        type: "select",
        required: true,
        errorMessage: "Payment Terms is required",
        options: [
            { label: "10 Days", value: "10_days" },
            { label: "20 Days", value: "20_days" },
            { label: "30 Days", value: "30_days" },
        ],
       },
    ],
       },
    address: {
        label: "Address",
        fields: [{
            name: "street_address",
            label: "Street Address",
            placeholder: "Enter Street Address",
            type: "text",
            required: true,
            errorMessage: "Street Address is required",
        },
        {
            name: "city",
            label: "City",
            placeholder: "Enter City",
            type: "text",
            required: true,
            errorMessage: "City is required",
        },
        {
            name: "state",
            label: "State",
            placeholder: "Enter State",
            type: "text",
            required: true,
            errorMessage: "State is required",
        },
        {
            name: "country",
            label: "Country",
            placeholder: "Enter Country",
            type: "text",
            required: true,
            errorMessage: "Country is required",
        },
        {
            name: "pincode",
            label: "Pincode",
            placeholder: "Enter Pincode",
            type: "text",
            required: true,
            errorMessage: "Pincode is required",
        },
        
    ],
},
contactInfo: {
    label: "Contact Information",
    fields: [{
        name: "contact_person_name",
        label: "Contact Person Name",
        placeholder: "Enter Contact Person Name",
        type: "text",
        required: true,
        errorMessage: "Contact Person Name is required",
    },
    {
        name: "designation",
        label: "Designation",
        placeholder: "Enter Designation",
        type: "text",
        required: false,
        errorMessage: "Designation is required",
    },
    {
        name: "email",
        label: "Email Address",
        placeholder: "Enter Email Address",
        type: "email",
        required: true,
        errorMessage: "Email Address is required",
    },
    {
        name: "mobile_number",
        label: "Mobile Number",
        placeholder: "Enter Mobile Number",
        type: "tel",
        required: true,
        errorMessage: "Mobile Number is required",
    },
    {
        name: "alternate_phone",
        label: "Alternate Phone",
        placeholder: "Enter Alternate Phone",
        type: "tel",
        required: false,
        errorMessage: "Alternate Phone is required",
    },
    {
        name: "company_website",
        label: "Company Website",
        placeholder: "Enter Company Website",
        type: "url",
        required: false,
        errorMessage: "Company Website is required",
    },
],
},
bankDetails: {
    label: "Bank Details",
    fields: [{
        name: "bank_name",
        label: "Bank Name",
        placeholder: "Enter Bank Name",
        type: "text",
        required: true,
        errorMessage: "Bank Name is required",
    },
    {
        name: "account_number",
        label: "Account Number",
        placeholder: "Enter Account Number",
        type: "text",
        required: true,
        errorMessage: "Account Number is required",
    },
    {
        name: "ifsc_code",
        label: "IFSC Code",
        placeholder: "Enter IFSC Code",
        type: "text",
        required: true,
        errorMessage: "IFSC Code is required",
    },
    {
        name: "account_type",
        label: "Account Type",
        placeholder: "Select Account Type",
        type: "select",
        required: true,
        errorMessage: "Account Type is required",
        options: [
            { label: "Savings", value: "savings" },
            { label: "Current", value: "current" },
        ],
    },
    {
        name: "branch_name",
        label: "Branch Name",
        placeholder: "Enter Branch Name",
        type: "text",
        required: false,
        errorMessage: "Branch Name is required",
    },
],
},
certificationsCompliance: {
    label: "Certifications & Compliance",
    fields: [{
        name: "iso_9001_2015",
        label: "ISO 9001:2015 Certified",
        type: "checkbox",
        required: false,
    },
    {
        name: "msme_registered",
        label: "MSME Registered",
        type: "checkbox",
        required: false,
    },
    {
        name: "dpiit_startup_registration",
        label: "DPIIT Startup Registration",
        type: "checkbox",
        required: false,
    },
    {
        name: "gmp_certified",
        label: "GMP Certified",
        type: "checkbox",
        required: false,
    },
   
],
},
documents: {
    label: "Documents upload",
    fields: [ {
        name: "pan_document",
        label: "PAN Document",
        placeholder: "Upload PAN Document",
        type: "file",
        required: false,
        errorMessage: "PAN Document is required",
    },
    {
        name: "aadhaar_document",
        label: "Aadhaar Document",
        placeholder: "Upload Aadhaar Document",
        type: "file",
        required: false,
        errorMessage: "Aadhaar Document is required",
    },
    {
        name: "bank_statement",
        label: "Bank Statement",
        placeholder: "Upload Bank Statement",
        type: "file",
        required: false,
        errorMessage: "Bank Statement is required",
    },
    {
        name: "gst_certificate",
        label: "GST Certificate",
        placeholder: "Upload GST Certificate",
        type: "file",
        required: false,
        errorMessage: "GST Certificate is required",
    },
    {
        name: "certification_document",
        label: "Certification Document",
        placeholder: "Upload Certification Document",
        type: "file",
        required: false,
        errorMessage: "Certification Document is required",
    },
],
},
}